[distribution]
DIST-CORE-01 ansible_host=192.168.99.11

[access]
ACC-01 ansible_host=192.168.99.12
ACC-02 ansible_host=192.168.99.13

[ovs:children]
distribution
access

[ovs:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
